name: Contains

on:
 push:
 issues:
 workflow_dispatch:
jobs:
 echo-contains:
  runs-on: ubuntu-latest
  steps:
   - name: display contains fn
     if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
     run: echo "display label name ${{github.event.issue.labels.*.name}}"
