name: Contains

on:
 issues:
 workflow_dispatch:
jobs:
 echo-contains:
  runs-on: ubuntu-latest
  steps:
   - run: echo "display event ${{github.event}}"
   - name: display contains fn
     if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
     run: echo "displaying bug"
