name: Deploy Functions

on:
 push:
  branches:
   - main
jobs:
 echo-deploy-function:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2

  - name: Setup Node.js
    uses: 
