name: Matrix

on:
 workflow_dispatch

jobs:
 echo-matrix:
  runs-on: ${{matrix.os}}
  strategy:
    matrix:
     node-version: [v22, v21]
     os: 
      - ubuntu-latest
      - windows
  steps:
   - name: Setup Node.js environment
     uses: actions/setup-node@v4.2.0
     with:
       node-version: ${{matrix.node-version}}
   - run: echo "os is ${{matrix.os}} and node version is ${{matrix.os}}"
       
    
  
