name: input

run-name: Input Debug - ${{inputs.debug}}
on:
 workflow_dispatch:
  inputs:
   debug:
    type: boolean
    default: false
jobs:
  echo-input-data:
   runs-on: ubuntu-latest
   steps:
    - run: echo "Print input"
    - run: exit 1
  echo-display:
   needs: echo-input-data
   runs-on: ubuntu-latest
   steps:
    - run: echo "Print data"
