name: secrets 

on:
 workflow_dispatch:

jobs:
  echo-secrets-job:
   runs-on: ubuntu-latest
   steps:
    - run: echo "Username is ${{secrets.USERNAME}}"
    - run: echo "Password is ${{secrets.PASSWORD}}"
    - run: echo "Password is ${{secrets.GITHUB_TOKEN}}"
    
